# yaml-language-server: $schema=https://raw.githubusercontent.com/akash-network/chain-sdk/refs/heads/main/ts/src/sdl/sdl-schema.yaml

version: "2.1"

services:
  web:
    image: baktun/hello-akash-world:1.0.0
    env:
      - APP_VERSION={{ .Env.APP_VERSION }}
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 512Mi

  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 10000

deployment:
  web:
    dcloud:
      profile: web
      count: 1
